-- Insert sample Pokemon TCG sets
INSERT INTO card_sets (set_code, name, description, game_type, release_date, total_cards, logo_url)
VALUES
    ('SV01', 'Scarlet & Violet Base Set', 'The first set of the Scarlet & Violet era', 'POKEMON', '2023-03-31', 258, 'https://images.pokemontcg.io/sv1/logo.png'),
    ('SV02', 'Paldea Evolved', 'Explore the Paldea region', 'POKEMON', '2023-06-09', 193, 'https://images.pokemontcg.io/sv2/logo.png'),
    ('SV03', 'Obsidian Flames', 'Ignite your collection', 'POKEMON', '2023-08-11', 197, 'https://images.pokemontcg.io/sv3/logo.png');

-- Insert ALL cards for SV01 Scarlet & Violet Base Set (258 cards)
INSERT INTO cards (card_set_id, card_number, name, rarity, variant, image_url, type, artist)
VALUES
    -- Standard Set: 1-198
    (1, '001', 'Pineco', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/1.png', 'Grass', 'Kouki Saitou'),
    (1, '002', 'Heracross', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/2.png', 'Grass', 'Kouki Saitou'),
    (1, '003', 'Shroomish', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/3.png', 'Grass', 'Kouki Saitou'),
    (1, '004', 'Breloom', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/4.png', 'Grass', 'Kouki Saitou'),
    (1, '005', 'Cacnea', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/5.png', 'Grass', 'Kouki Saitou'),
    (1, '006', 'Cacturne', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/6.png', 'Grass', 'Kouki Saitou'),
    (1, '007', 'Tropius', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/7.png', 'Grass', 'Kouki Saitou'),
    (1, '008', 'Scatterbug', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/8.png', 'Grass', 'Kouki Saitou'),
    (1, '009', 'Spewpa', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/9.png', 'Grass', 'Kouki Saitou'),
    (1, '010', 'Vivillon', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/10.png', 'Grass', 'Kouki Saitou'),
    (1, '011', 'Skiddo', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/11.png', 'Grass', 'Kouki Saitou'),
    (1, '012', 'Gogoat', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/12.png', 'Grass', 'Kouki Saitou'),
    (1, '013', 'Sprigatito', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/13.png', 'Grass', 'Kouki Saitou'),
    (1, '014', 'Floragato', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/14.png', 'Grass', 'Kouki Saitou'),
    (1, '015', 'Meowscarada', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/15.png', 'Grass', 'Kouki Saitou'),
    (1, '016', 'Tarountula', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/16.png', 'Grass', 'Kouki Saitou'),
    (1, '017', 'Tarountula', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/17.png', 'Grass', 'Kouki Saitou'),
    (1, '018', 'Tarountula', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/18.png', 'Grass', 'Kouki Saitou'),
    (1, '019', 'Spidops ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/19.png', 'Grass', '5ban Graphics'),
    (1, '020', 'Smoliv', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/20.png', 'Grass', 'Kouki Saitou'),
    (1, '021', 'Smoliv', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/21.png', 'Grass', 'Kouki Saitou'),
    (1, '022', 'Dolliv', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/22.png', 'Grass', 'Kouki Saitou'),
    (1, '023', 'Arboliva', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/23.png', 'Grass', 'Kouki Saitou'),
    (1, '024', 'Toedscool', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/24.png', 'Grass', 'Kouki Saitou'),
    (1, '025', 'Toedscool', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/25.png', 'Grass', 'Kouki Saitou'),
    (1, '026', 'Toedscruel', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/26.png', 'Grass', 'Kouki Saitou'),
    (1, '027', 'Capsakid', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/27.png', 'Grass', 'Kouki Saitou'),
    (1, '028', 'Capsakid', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/28.png', 'Grass', 'Kouki Saitou'),
    (1, '029', 'Scovillain', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/29.png', 'Grass', 'Kouki Saitou'),
    (1, '030', 'Growlithe', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/30.png', 'Fire', 'Narumi Sato'),
    (1, '031', 'Growlithe', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/31.png', 'Fire', 'Narumi Sato'),
    (1, '032', 'Arcanine ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/32.png', 'Fire', '5ban Graphics'),
    (1, '033', 'Houndour', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/33.png', 'Fire', 'Narumi Sato'),
    (1, '034', 'Houndoom', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/34.png', 'Fire', 'Narumi Sato'),
    (1, '035', 'Torkoal', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/35.png', 'Fire', 'Narumi Sato'),
    (1, '036', 'Fuecoco', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/36.png', 'Fire', 'Narumi Sato'),
    (1, '037', 'Crocalor', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/37.png', 'Fire', 'Narumi Sato'),
    (1, '038', 'Skeledirge', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/38.png', 'Fire', 'Narumi Sato'),
    (1, '039', 'Charcadet', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/39.png', 'Fire', 'Narumi Sato'),
    (1, '040', 'Charcadet', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/40.png', 'Fire', 'Narumi Sato'),
    (1, '041', 'Armarouge', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/41.png', 'Fire', 'Narumi Sato'),
    (1, '042', 'Slowpoke', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/42.png', 'Water', 'Kouki Saitou'),
    (1, '043', 'Slowbro', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/43.png', 'Water', 'Kouki Saitou'),
    (1, '044', 'Magikarp', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/44.png', 'Water', 'Kouki Saitou'),
    (1, '045', 'Gyarados ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/45.png', 'Water', '5ban Graphics'),
    (1, '046', 'Buizel', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/46.png', 'Water', 'Kouki Saitou'),
    (1, '047', 'Floatzel', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/47.png', 'Water', 'Kouki Saitou'),
    (1, '048', 'Alomomola', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/48.png', 'Water', 'Kouki Saitou'),
    (1, '049', 'Clauncher', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/49.png', 'Water', 'Kouki Saitou'),
    (1, '050', 'Clawitzer', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/50.png', 'Water', 'Kouki Saitou'),
    (1, '051', 'Bruxish', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/51.png', 'Water', 'Kouki Saitou'),
    (1, '052', 'Quaxly', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/52.png', 'Water', 'Kouki Saitou'),
    (1, '053', 'Quaxwell', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/53.png', 'Water', 'Kouki Saitou'),
    (1, '054', 'Quaquaval', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/54.png', 'Water', 'Kouki Saitou'),
    (1, '055', 'Wiglett', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/55.png', 'Water', 'Kouki Saitou'),
    (1, '056', 'Wiglett', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/56.png', 'Water', 'Kouki Saitou'),
    (1, '057', 'Wugtrio', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/57.png', 'Water', 'Kouki Saitou'),
    (1, '058', 'Cetoddle', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/58.png', 'Water', 'Kouki Saitou'),
    (1, '059', 'Cetoddle', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/59.png', 'Water', 'Kouki Saitou'),
    (1, '060', 'Cetitan', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/60.png', 'Water', 'Kouki Saitou'),
    (1, '061', 'Dondozo', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/61.png', 'Water', 'Kouki Saitou'),
    (1, '062', 'Tatsugiri', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/62.png', 'Water', 'Kouki Saitou'),
    (1, '063', 'Magnemite', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/63.png', 'Electric', 'PLANETA Tsuji'),
    (1, '064', 'Magneton', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/64.png', 'Electric', 'PLANETA Tsuji'),
    (1, '065', 'Magnezone ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/65.png', 'Electric', '5ban Graphics'),
    (1, '066', 'Mareep', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/66.png', 'Electric', 'PLANETA Tsuji'),
    (1, '067', 'Flaaffy', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/67.png', 'Electric', 'PLANETA Tsuji'),
    (1, '068', 'Pachirisu', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/68.png', 'Electric', 'PLANETA Tsuji'),
    (1, '069', 'Rotom', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/69.png', 'Electric', 'PLANETA Tsuji'),
    (1, '070', 'Rotom', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/70.png', 'Electric', 'PLANETA Tsuji'),
    (1, '071', 'Toxel', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/71.png', 'Electric', 'PLANETA Tsuji'),
    (1, '072', 'Toxtricity', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/72.png', 'Electric', 'PLANETA Tsuji'),
    (1, '073', 'Pawmi', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/73.png', 'Electric', 'PLANETA Tsuji'),
    (1, '074', 'Pawmi', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/74.png', 'Electric', 'PLANETA Tsuji'),
    (1, '075', 'Pawmo', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/75.png', 'Electric', 'PLANETA Tsuji'),
    (1, '076', 'Pawmot', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/76.png', 'Electric', 'PLANETA Tsuji'),
    (1, '077', 'Wattrel', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/77.png', 'Electric', 'PLANETA Tsuji'),
    (1, '078', 'Wattrel', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/78.png', 'Electric', 'PLANETA Tsuji'),
    (1, '079', 'Kilowattrel', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/79.png', 'Electric', 'PLANETA Tsuji'),
    (1, '080', 'Miraidon', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/80.png', 'Electric', 'PLANETA Tsuji'),
    (1, '081', 'Miraidon ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/81.png', 'Electric', '5ban Graphics'),
    (1, '082', 'Drowzee', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/82.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '083', 'Hypno', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/83.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '084', 'Ralts', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/84.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '085', 'Kirlia', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/85.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '086', 'Gardevoir ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/86.png', 'Psychic', '5ban Graphics'),
    (1, '087', 'Shuppet', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/87.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '088', 'Banette ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/88.png', 'Psychic', '5ban Graphics'),
    (1, '089', 'Drifloon', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/89.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '090', 'Drifblim', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/90.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '091', 'Flabébé', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/91.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '092', 'Floette', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/92.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '093', 'Florges', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/93.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '094', 'Dedenne', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/94.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '095', 'Dedenne', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/95.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '096', 'Klefki', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/96.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '097', 'Fidough', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/97.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '098', 'Fidough', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/98.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '099', 'Dachsbun', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/99.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '100', 'Flittle', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/100.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '101', 'Flittle', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/101.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '102', 'Flittle', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/102.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '103', 'Espathra', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/103.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '104', 'Greavard', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/104.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '105', 'Greavard', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/105.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '106', 'Houndstone', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/106.png', 'Psychic', 'Sanosuke Sakuma'),
    (1, '107', 'Mankey', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/107.png', 'Fighting', 'Oswaldo KATO'),
    (1, '108', 'Primeape', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/108.png', 'Fighting', 'Oswaldo KATO'),
    (1, '109', 'Annihilape', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/109.png', 'Fighting', 'Oswaldo KATO'),
    (1, '110', 'Meditite', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/110.png', 'Fighting', 'Oswaldo KATO'),
    (1, '111', 'Medicham', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/111.png', 'Fighting', 'Oswaldo KATO'),
    (1, '112', 'Riolu', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/112.png', 'Fighting', 'Oswaldo KATO'),
    (1, '113', 'Riolu', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/113.png', 'Fighting', 'Oswaldo KATO'),
    (1, '114', 'Lucario', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/114.png', 'Fighting', 'Oswaldo KATO'),
    (1, '115', 'Sandile', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/115.png', 'Fighting', 'Oswaldo KATO'),
    (1, '116', 'Krokorok', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/116.png', 'Fighting', 'Oswaldo KATO'),
    (1, '117', 'Krookodile', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/117.png', 'Fighting', 'Oswaldo KATO'),
    (1, '118', 'Hawlucha', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/118.png', 'Fighting', 'Oswaldo KATO'),
    (1, '119', 'Silicobra', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/119.png', 'Fighting', 'Oswaldo KATO'),
    (1, '120', 'Sandaconda', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/120.png', 'Fighting', 'Oswaldo KATO'),
    (1, '121', 'Stonjourner', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/121.png', 'Fighting', 'Oswaldo KATO'),
    (1, '122', 'Klawf', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/122.png', 'Fighting', 'Oswaldo KATO'),
    (1, '123', 'Great Tusk ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/123.png', 'Fighting', '5ban Graphics'),
    (1, '124', 'Koraidon', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/124.png', 'Fighting', 'Oswaldo KATO'),
    (1, '125', 'Koraidon ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/125.png', 'Fighting', '5ban Graphics'),
    (1, '126', 'Grimer', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/126.png', 'Dark', 'Miki Tanaka'),
    (1, '127', 'Muk', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/127.png', 'Dark', 'Miki Tanaka'),
    (1, '128', 'Seviper', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/128.png', 'Dark', 'Miki Tanaka'),
    (1, '129', 'Spiritomb', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/129.png', 'Dark', 'Miki Tanaka'),
    (1, '130', 'Croagunk', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/130.png', 'Dark', 'Miki Tanaka'),
    (1, '131', 'Toxicroak ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/131.png', 'Dark', '5ban Graphics'),
    (1, '132', 'Pawniard', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/132.png', 'Dark', 'Miki Tanaka'),
    (1, '133', 'Bisharp', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/133.png', 'Dark', 'Miki Tanaka'),
    (1, '134', 'Kingambit', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/134.png', 'Dark', 'Miki Tanaka'),
    (1, '135', 'Maschiff', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/135.png', 'Dark', 'Miki Tanaka'),
    (1, '136', 'Maschiff', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/136.png', 'Dark', 'Miki Tanaka'),
    (1, '137', 'Mabosstiff', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/137.png', 'Dark', 'Miki Tanaka'),
    (1, '138', 'Bombirdier', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/138.png', 'Dark', 'Miki Tanaka'),
    (1, '139', 'Forretress', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/139.png', 'Metal', 'Oswaldo KATO'),
    (1, '140', 'Varoom', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/140.png', 'Metal', 'Oswaldo KATO'),
    (1, '141', 'Varoom', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/141.png', 'Metal', 'Oswaldo KATO'),
    (1, '142', 'Revavroom', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/142.png', 'Metal', 'Oswaldo KATO'),
    (1, '143', 'Iron Treads ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/143.png', 'Metal', '5ban Graphics'),
    (1, '144', 'Chansey', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/144.png', 'Colorless', 'Akira Komayama'),
    (1, '145', 'Blissey', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/145.png', 'Colorless', 'Akira Komayama'),
    (1, '146', 'Zangoose', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/146.png', 'Colorless', 'Akira Komayama'),
    (1, '147', 'Zangoose', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/147.png', 'Colorless', 'Akira Komayama'),
    (1, '148', 'Starly', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/148.png', 'Colorless', 'Akira Komayama'),
    (1, '149', 'Staravia', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/149.png', 'Colorless', 'Akira Komayama'),
    (1, '150', 'Staraptor', 'RARE', NULL, 'https://images.pokemontcg.io/sv1/150.png', 'Colorless', 'Akira Komayama'),
    (1, '151', 'Skwovet', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/151.png', 'Colorless', 'Akira Komayama'),
    (1, '152', 'Greedent', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/152.png', 'Colorless', 'Akira Komayama'),
    (1, '153', 'Indeedee', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/153.png', 'Colorless', 'Akira Komayama'),
    (1, '154', 'Lechonk', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/154.png', 'Colorless', 'Akira Komayama'),
    (1, '155', 'Lechonk', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/155.png', 'Colorless', 'Akira Komayama'),
    (1, '156', 'Lechonk', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/156.png', 'Colorless', 'Akira Komayama'),
    (1, '157', 'Oinkologne', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/157.png', 'Colorless', 'Akira Komayama'),
    (1, '158', 'Oinkologne ex', 'ULTRA_RARE', 'ex', 'https://images.pokemontcg.io/sv1/158.png', 'Colorless', '5ban Graphics'),
    (1, '159', 'Tandemaus', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/159.png', 'Colorless', 'Akira Komayama'),
    (1, '160', 'Tandemaus', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/160.png', 'Colorless', 'Akira Komayama'),
    (1, '161', 'Maushold', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/161.png', 'Colorless', 'Akira Komayama'),
    (1, '162', 'Squawkabilly', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/162.png', 'Colorless', 'Akira Komayama'),
    (1, '163', 'Cyclizar', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/163.png', 'Colorless', 'Akira Komayama'),
    (1, '164', 'Cyclizar', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/164.png', 'Colorless', 'Akira Komayama'),
    (1, '165', 'Flamigo', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/165.png', 'Colorless', 'Akira Komayama'),

    -- Trainer Cards: 166-198
    (1, '166', 'Arven', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/166.png', 'Trainer', 'Ryota Murayama'),
    (1, '167', 'Beach Court', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/167.png', 'Trainer', 'Ryo Ueda'),
    (1, '168', 'Crushing Hammer', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/168.png', 'Trainer', 'Toyste Beach'),
    (1, '169', 'Defiance Band', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/169.png', 'Trainer', 'Toyste Beach'),
    (1, '170', 'Electric Generator', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/170.png', 'Trainer', 'Studio Bora Inc.'),
    (1, '171', 'Energy Retrieval', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/171.png', 'Trainer', 'Toyste Beach'),
    (1, '172', 'Energy Search', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/172.png', 'Trainer', 'Toyste Beach'),
    (1, '173', 'Energy Switch', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/173.png', 'Trainer', 'Toyste Beach'),
    (1, '174', 'Exp. Share', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/174.png', 'Trainer', 'Toyste Beach'),
    (1, '175', 'Jacq', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/175.png', 'Trainer', 'Sanosuke Sakuma'),
    (1, '176', 'Judge', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/176.png', 'Trainer', 'Hideki Ishikawa'),
    (1, '177', 'Katy', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/177.png', 'Trainer', 'Sanosuke Sakuma'),
    (1, '178', 'Mesagoza', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/178.png', 'Trainer', 'ORBITALLINK Inc.'),
    (1, '179', 'Miriam', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/179.png', 'Trainer', 'kirisAki'),
    (1, '180', 'Nemona', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/180.png', 'Trainer', 'Akira Egawa'),
    (1, '181', 'Nest Ball', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/181.png', 'Trainer', 'Toyste Beach'),
    (1, '182', 'Pal Pad', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/182.png', 'Trainer', 'Toyste Beach'),
    (1, '183', 'Penny', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/183.png', 'Trainer', 'kirisAki'),
    (1, '184', 'Picnic Basket', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/184.png', 'Trainer', 'Toyste Beach'),
    (1, '185', 'Poké Ball', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/185.png', 'Trainer', 'Toyste Beach'),
    (1, '186', 'Pokégear 3.0', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/186.png', 'Trainer', 'Toyste Beach'),
    (1, '187', 'Pokémon Catcher', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/187.png', 'Trainer', 'Toyste Beach'),
    (1, '188', 'Potion', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/188.png', 'Trainer', 'Toyste Beach'),
    (1, '189', 'Professor''s Research (Professor Sada)', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/189.png', 'Trainer', 'Naoki Saito'),
    (1, '190', 'Professor''s Research (Professor Turo)', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/190.png', 'Trainer', 'Naoki Saito'),
    (1, '191', 'Rare Candy', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/191.png', 'Trainer', 'Toyste Beach'),
    (1, '192', 'Rock Chestplate', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/192.png', 'Trainer', 'Toyste Beach'),
    (1, '193', 'Rocky Helmet', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/193.png', 'Trainer', 'Toyste Beach'),
    (1, '194', 'Switch', 'COMMON', NULL, 'https://images.pokemontcg.io/sv1/194.png', 'Trainer', 'Toyste Beach'),
    (1, '195', 'Team Star Grunt', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/195.png', 'Trainer', 'Akira Egawa'),
    (1, '196', 'Ultra Ball', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/196.png', 'Trainer', 'Toyste Beach'),
    (1, '197', 'Vitality Band', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/197.png', 'Trainer', 'Toyste Beach'),
    (1, '198', 'Youngster', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv1/198.png', 'Trainer', 'Hitoshi Ariga'),

    -- Secret Rares: 199-257
    (1, '199', 'Tarountula', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/199.png', 'Grass', 'Kagemaru Himeno'),
    (1, '200', 'Dolliv', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/200.png', 'Grass', 'Kariya'),
    (1, '201', 'Toedscool', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/201.png', 'Grass', 'sowsow'),
    (1, '202', 'Scovillain', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/202.png', 'Grass', 'Kouki Saitou'),
    (1, '203', 'Armarouge', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/203.png', 'Fire', 'OKACHEKE'),
    (1, '204', 'Slowpoke', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/204.png', 'Water', 'Hitoshi Ariga'),
    (1, '205', 'Clauncher', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/205.png', 'Water', 'Mitsuhiro Arita'),
    (1, '206', 'Wiglett', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/206.png', 'Water', 'Shibuzoh.'),
    (1, '207', 'Dondozo', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/207.png', 'Water', 'AKIRA EGAWA'),
    (1, '208', 'Pachirisu', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/208.png', 'Electric', 'Mitsuhiro Arita'),
    (1, '209', 'Pawmot', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/209.png', 'Electric', 'kantaro'),
    (1, '210', 'Drowzee', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/210.png', 'Psychic', 'Oswaldo KATO'),
    (1, '211', 'Ralts', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/211.png', 'Psychic', 'Kouki Saitou'),
    (1, '212', 'Kirlia', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/212.png', 'Psychic', 'Kouki Saitou'),
    (1, '213', 'Fidough', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/213.png', 'Psychic', 'Nisota Niso'),
    (1, '214', 'Greavard', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/214.png', 'Psychic', 'Miki Tanaka'),
    (1, '215', 'Riolu', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/215.png', 'Fighting', 'Kouki Saitou'),
    (1, '216', 'Sandile', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/216.png', 'Fighting', 'Kurata So'),
    (1, '217', 'Klawf', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/217.png', 'Fighting', 'sowsow'),
    (1, '218', 'Mabosstiff', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/218.png', 'Dark', 'Narumi Sato'),
    (1, '219', 'Bombirdier', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/219.png', 'Dark', 'Oswaldo KATO'),
    (1, '220', 'Kingambit', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/220.png', 'Dark', 'takuyoa'),
    (1, '221', 'Starly', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/221.png', 'Colorless', 'Narumi Sato'),
    (1, '222', 'Skwovet', 'SECRET_RARE', 'Illustration Rare', 'https://images.pokemontcg.io/sv1/222.png', 'Colorless', 'Yuka Morii'),
    (1, '223', 'Spidops ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/223.png', 'Grass', '5ban Graphics'),
    (1, '224', 'Arcanine ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/224.png', 'Fire', '5ban Graphics'),
    (1, '225', 'Gyarados ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/225.png', 'Water', '5ban Graphics'),
    (1, '226', 'Magnezone ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/226.png', 'Electric', '5ban Graphics'),
    (1, '227', 'Miraidon ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/227.png', 'Electric', '5ban Graphics'),
    (1, '228', 'Gardevoir ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/228.png', 'Psychic', '5ban Graphics'),
    (1, '229', 'Banette ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/229.png', 'Psychic', '5ban Graphics'),
    (1, '230', 'Great Tusk ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/230.png', 'Fighting', '5ban Graphics'),
    (1, '231', 'Koraidon ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/231.png', 'Fighting', '5ban Graphics'),
    (1, '232', 'Toxicroak ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/232.png', 'Dark', '5ban Graphics'),
    (1, '233', 'Iron Treads ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/233.png', 'Metal', '5ban Graphics'),
    (1, '234', 'Oinkologne ex', 'SECRET_RARE', 'Double Rare', 'https://images.pokemontcg.io/sv1/234.png', 'Colorless', '5ban Graphics'),
    (1, '235', 'Arven', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/235.png', 'Trainer', 'Sanosuke Sakuma'),
    (1, '236', 'Jacq', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/236.png', 'Trainer', 'Akira Egawa'),
    (1, '237', 'Katy', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/237.png', 'Trainer', 'kirisAki'),
    (1, '238', 'Miriam', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/238.png', 'Trainer', 'Naoki Saito'),
    (1, '239', 'Penny', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/239.png', 'Trainer', 'Megumi Mizutani'),
    (1, '240', 'Professor''s Research (Professor Sada)', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/240.png', 'Trainer', 'Naoki Saito'),
    (1, '241', 'Professor''s Research (Professor Turo)', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/241.png', 'Trainer', 'Naoki Saito'),
    (1, '242', 'Team Star Grunt', 'SECRET_RARE', 'Ultra Rare', 'https://images.pokemontcg.io/sv1/242.png', 'Trainer', 'AKIRA EGAWA'),
    (1, '243', 'Spidops ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/243.png', 'Grass', 'Ryota Murayama'),
    (1, '244', 'Miraidon ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/244.png', 'Electric', 'PLANETA Mochizuki'),
    (1, '245', 'Gardevoir ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/245.png', 'Psychic', 'kirisAki'),
    (1, '246', 'Great Tusk ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/246.png', 'Fighting', 'AKIRA EGAWA'),
    (1, '247', 'Koraidon ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/247.png', 'Fighting', 'PLANETA Mochizuki'),
    (1, '248', 'Iron Treads ex', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/248.png', 'Metal', 'AKIRA EGAWA'),
    (1, '249', 'Arven', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/249.png', 'Trainer', 'Ryota Murayama'),
    (1, '250', 'Jacq', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/250.png', 'Trainer', 'Sanosuke Sakuma'),
    (1, '251', 'Miriam', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/251.png', 'Trainer', 'Ryota Murayama'),
    (1, '252', 'Penny', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv1/252.png', 'Trainer', 'Megumi Mizutani'),
    (1, '253', 'Miraidon ex', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/253.png', 'Electric', '5ban Graphics'),
    (1, '254', 'Koraidon ex', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/254.png', 'Fighting', '5ban Graphics'),
    (1, '255', 'Nest Ball', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/255.png', 'Trainer', 'Toyste Beach'),
    (1, '256', 'Rare Candy', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/256.png', 'Trainer', 'Toyste Beach'),
    (1, '257', 'Basic Lightning Energy', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/257.png', 'Energy', 'Toyste Beach'),
    (1, '258', 'Basic Fighting Energy', 'SECRET_RARE', 'Hyper Rare', 'https://images.pokemontcg.io/sv1/258.png', 'Energy', 'Toyste Beach');

-- Insert sample cards for SV02
INSERT INTO cards (card_set_id, card_number, name, rarity, variant, image_url, type, artist)
VALUES
    (2, '001', 'Tangela', 'COMMON', NULL, 'https://images.pokemontcg.io/sv2/1.png', 'Grass', 'Kouki Saitou'),
    (2, '002', 'Tangrowth', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv2/2.png', 'Grass', 'Kouki Saitou'),
    (2, '193', 'Iono', 'SECRET_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv2/193.png', 'Trainer', 'Nagomi Nijo');

-- Insert sample cards for SV03
INSERT INTO cards (card_set_id, card_number, name, rarity, variant, image_url, type, artist)
VALUES
    (3, '001', 'Oddish', 'COMMON', NULL, 'https://images.pokemontcg.io/sv3/1.png', 'Grass', 'Saya Tsuruta'),
    (3, '002', 'Gloom', 'UNCOMMON', NULL, 'https://images.pokemontcg.io/sv3/2.png', 'Grass', 'Saya Tsuruta'),
    (3, '197', 'Charizard ex', 'ULTRA_RARE', 'Special Illustration Rare', 'https://images.pokemontcg.io/sv3/197.png', 'Fire', 'PLANETA Yamashita');
